package org.universAAL.ontology.cryptographic;

import java.util.ArrayList;
import java.util.List;

import org.universAAL.middleware.owl.ManagedIndividual;


/**
 * Ontological representation of Encryption in the cryptographic ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public abstract class Encryption extends CryptographicTechnique {
  public static final String MY_URI = CryptographicOntology.NAMESPACE
    + "Encryption";
  public static final String PROP_KEY = CryptographicOntology.NAMESPACE
    + "key";


  public Encryption () {
    super();
  }
  
  public Encryption (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {
    if (PROP_KEY.equals(propURI))
      return PROP_SERIALIZATION_FULL;
    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed() 
      && hasProperty(PROP_KEY);
  }

  public EncryptionKey[] getKey() {
    Object propList = getProperty(PROP_KEY);
    if (propList instanceof List)
      return (EncryptionKey[]) ((List) propList).toArray(new EncryptionKey[0]);
    else if (propList != null)
      return new EncryptionKey[] {(EncryptionKey)propList}; // Handle special case of a single item not contained in a list
    return new EncryptionKey[0];
  }

  public void addKey(EncryptionKey newValue) {
    Object propList = getProperty(PROP_KEY);
    List newList;
    if (propList instanceof List)
      newList = (List)propList;
    else {
      newList = new ArrayList();
      if (propList != null)
        newList.add(propList); // Handle special case of a single previous item not contained in a list
    }
    newList.add(newValue);
    changeProperty(PROP_KEY, newList);
  }
  

  public void setKey(EncryptionKey[] propertyValue) {
    List propList = new ArrayList(propertyValue.length);
    for (int i = 0; i < propertyValue.length; i++) {
      propList.add(propertyValue[i]);
    }
    changeProperty(PROP_KEY, propList);
  }

}
