package org.universAAL.ontology.cryptographic;

import org.universAAL.middleware.owl.ManagedIndividual;


/**
 * Ontological representation of EncryptionKey in the cryptographic ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public abstract class EncryptionKey extends ManagedIndividual {
  public static final String MY_URI = CryptographicOntology.NAMESPACE
    + "EncryptionKey";


  public EncryptionKey () {
    super();
  }
  
  public EncryptionKey (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {
    return PROP_SERIALIZATION_FULL;
  } 

  public boolean isWellFormed() {
	return super.isWellFormed() ;
  }

}
