package org.universAAL.ontology.cryptographic;



/**
 * Ontological representation of MultidestinationEncryptedResource in the cryptographic ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class MultidestinationEncryptedResource extends EncryptedResource {
  public static final String MY_URI = CryptographicOntology.NAMESPACE
    + "MultidestinationEncryptedResource";
  public static final String PROP_KEY = CryptographicOntology.NAMESPACE
    + "key";


  public MultidestinationEncryptedResource () {
    super();
  }
  
  public MultidestinationEncryptedResource (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {
    if (PROP_KEY.equals(propURI))
      return PROP_SERIALIZATION_FULL;
    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed() 
      && hasProperty(PROP_KEY);
  }

  public EncryptionKey getKey() {
    return (EncryptionKey)getProperty(PROP_KEY);
  }		

  public void setKey(EncryptionKey newPropValue) {
    if (newPropValue != null)
      changeProperty(PROP_KEY, newPropValue);
  }		

}
