/*******************************************************************************
 * Copyright 2016 Universidad Politécnica de Madrid UPM
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.universAAL.ontology.cryptographic;



/**
 * Ontological representation of SymetricEncryption in the cryptographic ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public abstract class SymmetricEncryption extends Encryption {
  public static final String MY_URI = CryptographicOntology.NAMESPACE
    + "SymmetricEncryption";
  public static final String PROP_SIMPLE_KEY = CryptographicOntology.NAMESPACE
    + "simpleKey";


  public SymmetricEncryption () {
    super();
  }
  
  public SymmetricEncryption (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {
    if (PROP_SIMPLE_KEY.equals(propURI))
      return PROP_SERIALIZATION_FULL;
    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed() 
      && hasProperty(PROP_SIMPLE_KEY);
  }

  public SimpleKey getSimpleKey() {
    return (SimpleKey)getProperty(PROP_SIMPLE_KEY);
  }		

  public void setSimpleKey(SimpleKey newPropValue) {
    if (newPropValue != null)
      changeProperty(PROP_SIMPLE_KEY, newPropValue);
  }

  /**{@inheritDoc} */
  public EncryptionKey[] getKey() {
	  if (hasProperty(PROP_SIMPLE_KEY))
		  return new EncryptionKey[]{getSimpleKey()};
	  else
		  return new EncryptionKey[0];
  }

  /**{@inheritDoc} */
  public void addKey(EncryptionKey newValue) {
	  setSimpleKey((SimpleKey) newValue);
  }

  /**{@inheritDoc} */
  public void setKey(EncryptionKey[] propertyValue) {
	  setSimpleKey((SimpleKey) propertyValue[0]);
  }		

}
