package org.universAAL.ontology.sysinfo;

import org.universAAL.middleware.owl.ManagedIndividual;

/**
 * Ontological representation of Descriptor in the sysinfo ontology. Methods
 * included in this class are the mandatory ones for representing an ontological
 * concept in Java classes for the universAAL platform. In addition getters and
 * setters for properties are included.
 * 
 * @author
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class Descriptor extends ManagedIndividual {
    public static final String MY_URI = SysinfoOntology.NAMESPACE
	    + "Descriptor";
    public static final String PROP__SERIALIZED_VALUE = SysinfoOntology.NAMESPACE
	    + "SerializedValue";

    public Descriptor() {
	super();
    }

    public Descriptor(String uri) {
	super(uri);
    }

    public String getClassURI() {
	return MY_URI;
    }

    public int getPropSerializationType(String propURI) {
	return PROP_SERIALIZATION_FULL;
    }

    public boolean isWellFormed() {
	return true;
    }

    public String getSerializedValue() {
	return (String) getProperty(PROP__SERIALIZED_VALUE);
    }

    public void setSerializedValue(String newPropValue) {
	if (newPropValue != null)
	    changeProperty(PROP__SERIALIZED_VALUE, newPropValue);
    }

}
