/*******************************************************************************
 * Copyright 2013 Universidad PolitĂ©cnica de Madrid
 * Copyright 2013 Ericsson Nikola Tesla d.d.
 *
 * See the NOTICE file distributed with this work for additional 
 * information regarding copyright ownership
 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *	
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.universAAL.ontology.recommendations;


/**
 * Ontological representation of GridLayout in the recommendations ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * <pre>
 * <code> 
 * {@link Group} f = new Group(...);
 * f.addAppearanceRecommendation(new GridLayout(2,2));
 * </code></pre>
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class GridLayout extends Layout {
  public static final String MY_URI = RecommendationsOntology.NAMESPACE
    + "GridLayout";
  public static final String PROP_NUMBER_OF_COLUMNS = RecommendationsOntology.NAMESPACE+"colNumber";
  public static final String PROP_NUMBER_OF_ROWS = RecommendationsOntology.NAMESPACE+"rowNumber";

  public GridLayout () {
    super();
  }
  
  public GridLayout (int cols, int rows) {
	    super();
	    this.setCols(cols).setRows(rows);
	  }
  
  public GridLayout (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {

	  if (propURI.equals(PROP_NUMBER_OF_COLUMNS)
			  || propURI.equals(PROP_NUMBER_OF_ROWS)){
		  return PROP_SERIALIZATION_FULL;
	  }
	  
    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed()
			&& hasProperty(PROP_NUMBER_OF_COLUMNS)
			&& hasProperty(PROP_NUMBER_OF_ROWS);
  }

  public int getColCount(){
	  return ((Integer) getProperty(PROP_NUMBER_OF_COLUMNS)).intValue();
  }
  
  public GridLayout setCols(int col){
	  changeProperty(PROP_NUMBER_OF_COLUMNS, Integer.valueOf(col));
	  return this;
  }
  
  public int getRowCount(){
	  return ((Integer) getProperty(PROP_NUMBER_OF_ROWS)).intValue();
  }
  
  public GridLayout setRows(int col){
	  changeProperty(PROP_NUMBER_OF_ROWS, Integer.valueOf(col));
	  return this;
  }


}
