/*******************************************************************************
 * Copyright 2013 Universidad PolitĂ©cnica de Madrid
 * Copyright 2013 Ericsson Nikola Tesla d.d.
 *
 * See the NOTICE file distributed with this work for additional 
 * information regarding copyright ownership
 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *	
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.universAAL.ontology.recommendations;

import org.universAAL.middleware.ui.rdf.FormControl;



/**
 * Ontological representation of HorizontalAlignment in the recommendations ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * <BR>
 * 
 * Possible options are:
 * <ul>
 * <li> left
 * <li> center
 * <li> right
 * </ul>
 * 
 * <pre><code>
 * {@link FormControl} fc = ...;
 * fc.addAppearanceRecommendation(HorizontalAlignment.left);
 * 
 * //OR
 * 
 * fc.addAppearanceRecommendation(HorizontalAlignment.center);
 * 
 * //OR
 * 
 * fc.addAppearanceRecommendation(HorizontalAlignment.right);
 * </code></pre>
 * 
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class HorizontalAlignment extends Alignment {
  public static final String MY_URI = RecommendationsOntology.NAMESPACE
    + "HorizontalAlignment";


  static final String INST_LEFT = RecommendationsOntology.NAMESPACE + "leftHorizontalAlignment";
  static final String INST_CENTER = RecommendationsOntology.NAMESPACE + "centerHorizontalAlignment";
  static final String INST_RIGHT = RecommendationsOntology.NAMESPACE + "rightHorizontalAlignment";
  
  public static HorizontalAlignment left;
  public static HorizontalAlignment center;
  public static HorizontalAlignment right;


  public HorizontalAlignment () {
    super();
  }
  
  public HorizontalAlignment (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {

    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed();
  }


}
