/*******************************************************************************
 * Copyright 2013 Universidad PolitĂ©cnica de Madrid
 * Copyright 2013 Ericsson Nikola Tesla d.d.
 *
 * See the NOTICE file distributed with this work for additional 
 * information regarding copyright ownership
 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *	
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.universAAL.ontology.recommendations;

import org.universAAL.middleware.ui.rdf.FormControl;



/**
 * Ontological representation of VerticalAlignment in the recommendations ontology. 
 * Methods included in this class are the mandatory ones for representing an
 * ontological concept in Java classes for the universAAL platform. In addition
 * getters and setters for properties are included.
 * 
 * <BR>
 * 
 * Possible options are:
 * <ul>
 * <li> top
 * <li> middle
 * <li> bottom
 * </ul>
 * 
 * <pre><code>
 * {@link FormControl} fc = ...;
 * fc.addAppearanceRecommendation(VerticalAlignment.top);
 * 
 * //OR
 * 
 * fc.addAppearanceRecommendation(VerticalAlignment.middle);
 * 
 * //OR
 * 
 * fc.addAppearanceRecommendation(VerticalAlignment.bottom);
 * </code></pre>
 * @author 
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public class VerticalAlignment extends Alignment {
  public static final String MY_URI = RecommendationsOntology.NAMESPACE
     + "VerticalAlignment";

  static final String INST_TOP = RecommendationsOntology.NAMESPACE + "topAlignment";
  static final String INST_MIDDLE = RecommendationsOntology.NAMESPACE + "middleAlignment";
  static final String INST_BOTTOM = RecommendationsOntology.NAMESPACE + "bottomAlignment";
  
  public static VerticalAlignment top;
  public static VerticalAlignment middle;
  public static VerticalAlignment bottom;



  public VerticalAlignment () {
    super();
  }
  
  public VerticalAlignment (String uri) {
    super(uri);
  }

  public String getClassURI() {
    return MY_URI;
  }
  
  public int getPropSerializationType(String propURI) {

    return super.getPropSerializationType(propURI);
  } 

  public boolean isWellFormed() {
	return super.isWellFormed();
  }

}
